"use client";
import ThemeProvider from '@/theme/ThemeProvider'
import './globals.css'
import {  Container } from '@chakra-ui/react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ThemeProvider>
      <Container maxW="container.sm"  >

        {children}
      </Container>
    </ThemeProvider>
  )
}
